typography_spectrum: 0.07205852027982473
color:
  brandStrength: 0.10067922831512988
  lightness: 0.23497411655262113
  saturation: 0.538480804534629
  rhythmicContrast: 0.6319908427540213
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.011213732417672873
analytics:
  google: >-
    https://testing.thegrid.io/app/site/design?siteID=158737e6-e938-42ff-bd7c-5f997186e36b
name: chikwendu
navigation:
  - name: Misadventures of learning with kids
    url: 'https://learningwithkidsblog.wordpress.com/'
    type: external
  - name: Take me with you - Traveling without borders
    url: 'https://akukoiro.wordpress.com/'
    type: external
