layout_spectrum: 0.7526987795718014
typography_spectrum: 0.9403122037183493
color:
  brandStrength: 0.9534109176602215
  lightness: 0.05452860309742391
  saturation: 0.2516622873954475
  rhythmicContrast: 0.22753709205426276
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
analytics:
  google: >-
    https://testing.thegrid.io/app/site/design?siteID=158737e6-e938-42ff-bd7c-5f997186e36b
name: chikwendu
navigation:
  - name: Misadventures of learning with kids
    url: 'https://learningwithkidsblog.wordpress.com/'
    type: external
  - name: Take me with you - Traveling without borders
    url: 'https://akukoiro.wordpress.com/'
    type: external
title: We Live Here
